import type { Metadata } from "next";
import Link from "next/link";
import { Footer } from "@/components/Footer";
import { PublicNav } from "@/components/PublicNav";

export const metadata: Metadata = {
  title: "Terms of Service | Lettr",
  description: "The terms that govern your use of Lettr.",
  alternates: { canonical: "/terms" },
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <main className="flex-1 flex flex-col bg-cream text-ink">
      <PublicNav />
      <div className="max-w-3xl mx-auto w-full px-4 sm:px-8 py-12 sm:py-16 flex-1">
        <p className="text-sm font-extrabold uppercase tracking-[0.12em] text-brand-blue mb-3">Legal</p>
        <h1 className="font-brand font-extrabold text-[40px] sm:text-[52px] leading-[1.02] tracking-tight mb-3">Terms of Service</h1>
        <p className="inline-block bg-gold-soft text-sm font-bold px-3 py-1 rounded-full mb-10">Last updated: July 2026</p>

        <div className="prose-content bg-white border border-rule rounded-[28px] p-6 sm:p-10 space-y-8 text-[16px] leading-relaxed">
          <section>
            <h2 className="font-brand font-extrabold text-xl tracking-tight mb-2">Using Lettr</h2>
            <p className="text-slate">
              Lettr is a resume-building tool. You&apos;re responsible for the accuracy of the
              information you put into your resume — we help you write and format it, but we
              don&apos;t verify factual claims about your work history.
            </p>
          </section>

          <section>
            <h2 className="font-brand font-extrabold text-xl tracking-tight mb-2">AI-generated content</h2>
            <p className="text-slate">
              Bullet points, summaries, cover letters, and resignation letters generated by
              Lettr&apos;s AI features are suggestions, not guarantees. Review everything before
              using it — you&apos;re responsible for what you ultimately submit to an employer.
            </p>
          </section>

          <section>
            <h2 className="font-brand font-extrabold text-xl tracking-tight mb-2">Your content</h2>
            <p className="text-slate">
              You own what you write. We don&apos;t claim any ownership over your resume content,
              and we don&apos;t use it for anything other than providing the service back to you.
            </p>
          </section>

          <section>
            <h2 className="font-brand font-extrabold text-xl tracking-tight mb-2">Free and Pro plans</h2>
            <p className="text-slate">
              The Free plan includes 1 resume and 3 PDF downloads. Pro is a monthly subscription
              billed through Stripe, cancellable at any time from your billing portal — you keep
              Pro access through the end of the period you&apos;ve already paid for. Current
              pricing is always shown on our{" "}
              <Link href="/pricing" className="font-bold text-brand-blue hover:underline">Pricing page</Link>.
            </p>
          </section>

          <section>
            <h2 className="font-brand font-extrabold text-xl tracking-tight mb-2">Acceptable use</h2>
            <p className="text-slate">
              Don&apos;t use Lettr to generate fraudulent credentials, impersonate someone else, or
              abuse the AI features to generate content unrelated to resume/career writing. We may
              suspend accounts that misuse the service.
            </p>
          </section>

          <section>
            <h2 className="font-brand font-extrabold text-xl tracking-tight mb-2">No warranty</h2>
            <p className="text-slate">
              Lettr is provided as-is. We work to keep it reliable, but we don&apos;t guarantee
              uninterrupted availability or that AI-generated content will get you a specific
              outcome like an interview or job offer.
            </p>
          </section>

          <section>
            <h2 className="font-brand font-extrabold text-xl tracking-tight mb-2">Changes</h2>
            <p className="text-slate">
              We may update these terms as the product changes. Material changes will be reflected
              here with an updated date.
            </p>
          </section>

          <section>
            <h2 className="font-brand font-extrabold text-xl tracking-tight mb-2">Contact</h2>
            <p className="text-slate">
              Questions about these terms? Reach out via{" "}
              <Link href="/support" className="font-bold text-brand-blue hover:underline">our support page</Link>.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </main>
  );
}
