import Link from "next/link";
import { Footer } from "@/components/Footer";
import { PublicNav } from "@/components/PublicNav";

export default function TermsPage() {
  return (
    <main className="flex-1 flex flex-col">
      <PublicNav />
      <div className="max-w-2xl mx-auto w-full px-8 py-16 flex-1">
        <p className="text-xs uppercase tracking-wide text-seal font-semibold mb-2">Legal</p>
        <h1 className="font-display font-bold text-3xl mb-2">Terms of Service</h1>
        <p className="text-ink-soft text-sm mb-10">Last updated: July 2026</p>

        <div className="prose-content space-y-8 text-sm leading-relaxed">
          <section>
            <h2 className="font-display font-semibold text-lg mb-2">Using Lettr</h2>
            <p className="text-ink-soft">
              Lettr is a resume-building tool. You&apos;re responsible for the accuracy of the
              information you put into your resume — we help you write and format it, but we
              don&apos;t verify factual claims about your work history.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg mb-2">AI-generated content</h2>
            <p className="text-ink-soft">
              Bullet points, summaries, cover letters, and resignation letters generated by
              Lettr&apos;s AI features are suggestions, not guarantees. Review everything before
              using it — you&apos;re responsible for what you ultimately submit to an employer.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg mb-2">Your content</h2>
            <p className="text-ink-soft">
              You own what you write. We don&apos;t claim any ownership over your resume content,
              and we don&apos;t use it for anything other than providing the service back to you.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg mb-2">Free and Pro plans</h2>
            <p className="text-ink-soft">
              The Free plan includes 1 resume and 3 PDF downloads. Pro is a monthly subscription
              billed through Stripe, cancellable at any time from your billing portal — you keep
              Pro access through the end of the period you&apos;ve already paid for. Current
              pricing is always shown on our{" "}
              <Link href="/pricing" className="text-seal hover:underline">Pricing page</Link>.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg mb-2">Acceptable use</h2>
            <p className="text-ink-soft">
              Don&apos;t use Lettr to generate fraudulent credentials, impersonate someone else, or
              abuse the AI features to generate content unrelated to resume/career writing. We may
              suspend accounts that misuse the service.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg mb-2">No warranty</h2>
            <p className="text-ink-soft">
              Lettr is provided as-is. We work to keep it reliable, but we don&apos;t guarantee
              uninterrupted availability or that AI-generated content will get you a specific
              outcome like an interview or job offer.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg mb-2">Changes</h2>
            <p className="text-ink-soft">
              We may update these terms as the product changes. Material changes will be reflected
              here with an updated date.
            </p>
          </section>

          <section>
            <h2 className="font-display font-semibold text-lg mb-2">Contact</h2>
            <p className="text-ink-soft">
              Questions about these terms? Reach out via{" "}
              <Link href="/support" className="text-seal hover:underline">our support page</Link>.
            </p>
          </section>
        </div>
      </div>
      <Footer />
    </main>
  );
}
